// Copyright 1998-2016 Epic Games, Inc. All Rights Reserved.

#pragma once

#include "Engine.h"
#include "BiasedBPLibrary.generated.h"

DECLARE_LOG_CATEGORY_EXTERN(BiasedLog, Log, All);

typedef TPair<FDieFace, int32> FDieFaceAlias;

/**
* Data structure describing the face of a biased die. The value is the result if the die lands
* on this face and the probability is the likely hood of this face being rolled
*/
USTRUCT(BlueprintType)
struct FDieFace 
{
	GENERATED_BODY()

	FDieFace() {}

	FDieFace(const FDieFace& DieFace) : Value(DieFace.Value), Probability(DieFace.Probability) {}

	FDieFace(int32 InValue, float InProbability) : Value(InValue), Probability(InProbability) {}

	/**
	* The result if the die lands on this face
	*/
	UPROPERTY(BlueprintReadWrite)
	int32 Value;

	/**
	* The probability of this face being rolled
	*/
	UPROPERTY(BlueprintReadWrite)
	float Probability;
};

/**
* Data structure that holds preprocessed data describing a biased die, which can be used to roll 
* biased dice in constant time.
*/
USTRUCT(BlueprintType)
struct FBiasedDieData
{
	GENERATED_BODY()

	//operator[]
	const FDieFaceAlias& operator[] (int32 Index) const
	{
		return ProbablilityPairs[Index];
	}

	//NumFaces()
	int NumFaces() const
	{
		return ProbablilityPairs.Num();
	}

private:
	friend class UBiasedBPLibrary;
	
	void AddDieFaceAlias(FDieFace DieFace, int32 Alias)
	{
		ProbablilityPairs.Push(FDieFaceAlias(TPairInitializer<FDieFace, int32>(DieFace, Alias)));
	}

	TArray< FDieFaceAlias > ProbablilityPairs;

};

/* 
*	Function library class.
*	
*/
UCLASS()
class UBiasedBPLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_UCLASS_BODY()

	/**
	* Preprocesses a list of die faces and generates data in a format that allows for constant 
	* time generation of biased die rolls of the die.
	*
	* The sum of the probability of the die faces should be equal to 1 for the generation to 
	* be successful.
	*
	* @param Faces List of die faces you want to prepare for rolling.
	* @param OutBiasedDieData Out Parameter. The preprocessed die data that is ready to be rolled.
	* @return Whether the preparation of the data was successful or not.
	*/
	UFUNCTION(BlueprintCallable, meta = (DisplayName = "Generate Data For Biased Die Rolls", Keywords = "biased generate die"), Category = "Biased")
	static bool GenerateBiasedDieData(const TArray<FDieFace>& Faces, FBiasedDieData& OutBiasedDieData);

	/**
	* Roll a biased die
	*
	* @param BiasedDieData The die data generated by GenerateBiasedDieData for the die you wish to roll.
	* @return The result of the die roll.
	*/
	UFUNCTION(BlueprintCallable, meta = (DisplayName = "Roll Biased Die", Keywords = "biased roll die"), Category = "Biased")
	static int32 RollBiasedDie(const FBiasedDieData& BiasedDieData);

	/**
	* Roll a biased die using a random stream
	*
	* @param BiasedDieData The die data generated by GenerateBiasedDieData for the die you wish to roll.
	* @param RandomStream The random stream to generate random numbers from
	* @return The result of the die roll.
	*/
	UFUNCTION(BlueprintCallable, meta = (DisplayName = "Roll Biased Die From Stream", Keywords = "biased roll die stream"), Category = "Biased")
	static int32 RollBiasedDieFromStream(const FBiasedDieData& BiasedDieData, const FRandomStream& RandomStream);

private:
	
	static int32 InternalRollBiasedDice(const FBiasedDieData &BiasedDieData, int32 RandIndex, float RandRoll);
};
